# Generated by Django 2.1.1 on 2018-10-09 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_cart_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
