# Generated by Django 2.1.1 on 2018-10-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_cart_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
